/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and re-run the "tsr-schema-types" tool to regenerate this file.
 */

import { DeviceType } from 'timeline-state-resolver-types'
import CommonOptions = require('./$schemas/common-options.json')
import { generateTranslation } from './lib.js'
import { stringifyActionSchema, stringifyMappingSchema, TSRManifest } from './manifestLib.js'
import AbstractActions = require('./$schemas/generated/abstract/actions.json')
import AbstractOptions = require('./$schemas/generated/abstract/options.json')
import AbstractMappings = require('./$schemas/generated/abstract/mappings.json')
import AtemActions = require('./$schemas/generated/atem/actions.json')
import AtemOptions = require('./$schemas/generated/atem/options.json')
import AtemMappings = require('./$schemas/generated/atem/mappings.json')
import CasparCGActions = require('./$schemas/generated/casparCG/actions.json')
import CasparCGOptions = require('./$schemas/generated/casparCG/options.json')
import CasparCGMappings = require('./$schemas/generated/casparCG/mappings.json')
import HttpSendActions = require('./$schemas/generated/httpSend/actions.json')
import HttpSendOptions = require('./$schemas/generated/httpSend/options.json')
import HttpSendMappings = require('./$schemas/generated/httpSend/mappings.json')
import HttpWatcherOptions = require('./$schemas/generated/httpWatcher/options.json')
import HttpWatcherMappings = require('./$schemas/generated/httpWatcher/mappings.json')
import HyperdeckActions = require('./$schemas/generated/hyperdeck/actions.json')
import HyperdeckOptions = require('./$schemas/generated/hyperdeck/options.json')
import HyperdeckMappings = require('./$schemas/generated/hyperdeck/mappings.json')
import KairosActions = require('./$schemas/generated/kairos/actions.json')
import KairosOptions = require('./$schemas/generated/kairos/options.json')
import KairosMappings = require('./$schemas/generated/kairos/mappings.json')
import LawoOptions = require('./$schemas/generated/lawo/options.json')
import LawoMappings = require('./$schemas/generated/lawo/mappings.json')
import MultiOscOptions = require('./$schemas/generated/multiOsc/options.json')
import MultiOscMappings = require('./$schemas/generated/multiOsc/mappings.json')
import ObsOptions = require('./$schemas/generated/obs/options.json')
import ObsMappings = require('./$schemas/generated/obs/mappings.json')
import OscOptions = require('./$schemas/generated/osc/options.json')
import OscMappings = require('./$schemas/generated/osc/mappings.json')
import PanasonicPTZActions = require('./$schemas/generated/panasonicPTZ/actions.json')
import PanasonicPTZOptions = require('./$schemas/generated/panasonicPTZ/options.json')
import PanasonicPTZMappings = require('./$schemas/generated/panasonicPTZ/mappings.json')
import PharosActions = require('./$schemas/generated/pharos/actions.json')
import PharosOptions = require('./$schemas/generated/pharos/options.json')
import PharosMappings = require('./$schemas/generated/pharos/mappings.json')
import QuantelActions = require('./$schemas/generated/quantel/actions.json')
import QuantelOptions = require('./$schemas/generated/quantel/options.json')
import QuantelMappings = require('./$schemas/generated/quantel/mappings.json')
import ShotokuOptions = require('./$schemas/generated/shotoku/options.json')
import ShotokuMappings = require('./$schemas/generated/shotoku/mappings.json')
import SingularLiveOptions = require('./$schemas/generated/singularLive/options.json')
import SingularLiveMappings = require('./$schemas/generated/singularLive/mappings.json')
import SisyfosActions = require('./$schemas/generated/sisyfos/actions.json')
import SisyfosOptions = require('./$schemas/generated/sisyfos/options.json')
import SisyfosMappings = require('./$schemas/generated/sisyfos/mappings.json')
import SofieChefActions = require('./$schemas/generated/sofieChef/actions.json')
import SofieChefOptions = require('./$schemas/generated/sofieChef/options.json')
import SofieChefMappings = require('./$schemas/generated/sofieChef/mappings.json')
import TcpSendActions = require('./$schemas/generated/tcpSend/actions.json')
import TcpSendOptions = require('./$schemas/generated/tcpSend/options.json')
import TcpSendMappings = require('./$schemas/generated/tcpSend/mappings.json')
import TelemetricsOptions = require('./$schemas/generated/telemetrics/options.json')
import TelemetricsMappings = require('./$schemas/generated/telemetrics/mappings.json')
import TricasterOptions = require('./$schemas/generated/tricaster/options.json')
import TricasterMappings = require('./$schemas/generated/tricaster/mappings.json')
import UdpSendActions = require('./$schemas/generated/udpSend/actions.json')
import UdpSendOptions = require('./$schemas/generated/udpSend/options.json')
import UdpSendMappings = require('./$schemas/generated/udpSend/mappings.json')
import ViscaOverIPActions = require('./$schemas/generated/viscaOverIP/actions.json')
import ViscaOverIPOptions = require('./$schemas/generated/viscaOverIP/options.json')
import ViscaOverIPMappings = require('./$schemas/generated/viscaOverIP/mappings.json')
import VizMSEActions = require('./$schemas/generated/vizMSE/actions.json')
import VizMSEOptions = require('./$schemas/generated/vizMSE/options.json')
import VizMSEMappings = require('./$schemas/generated/vizMSE/mappings.json')
import VmixActions = require('./$schemas/generated/vmix/actions.json')
import VmixOptions = require('./$schemas/generated/vmix/options.json')
import VmixMappings = require('./$schemas/generated/vmix/mappings.json')
import WebsocketClientActions = require('./$schemas/generated/websocketClient/actions.json')
import WebsocketClientOptions = require('./$schemas/generated/websocketClient/options.json')

export const builtinDeviceManifest: TSRManifest = {
	commonOptions: JSON.stringify(CommonOptions),
	subdevices: {
		[DeviceType.ABSTRACT]: {
			displayName: generateTranslation('Abstract'),
			actions: AbstractActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(AbstractOptions),
			mappingsSchemas: stringifyMappingSchema(AbstractMappings),
		},
		[DeviceType.ATEM]: {
			displayName: generateTranslation('Atem'),
			actions: AtemActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(AtemOptions),
			mappingsSchemas: stringifyMappingSchema(AtemMappings),
		},
		[DeviceType.CASPARCG]: {
			displayName: generateTranslation('Caspar CG'),
			actions: CasparCGActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(CasparCGOptions),
			mappingsSchemas: stringifyMappingSchema(CasparCGMappings),
		},
		[DeviceType.HTTPSEND]: {
			displayName: generateTranslation('Http Send'),
			actions: HttpSendActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(HttpSendOptions),
			mappingsSchemas: stringifyMappingSchema(HttpSendMappings),
		},
		[DeviceType.HTTPWATCHER]: {
			displayName: generateTranslation('Http Watcher'),
			configSchema: JSON.stringify(HttpWatcherOptions),
			mappingsSchemas: stringifyMappingSchema(HttpWatcherMappings),
		},
		[DeviceType.HYPERDECK]: {
			displayName: generateTranslation('Hyperdeck'),
			actions: HyperdeckActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(HyperdeckOptions),
			mappingsSchemas: stringifyMappingSchema(HyperdeckMappings),
		},
		[DeviceType.KAIROS]: {
			displayName: generateTranslation('Kairos'),
			actions: KairosActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(KairosOptions),
			mappingsSchemas: stringifyMappingSchema(KairosMappings),
		},
		[DeviceType.LAWO]: {
			displayName: generateTranslation('Lawo'),
			configSchema: JSON.stringify(LawoOptions),
			mappingsSchemas: stringifyMappingSchema(LawoMappings),
		},
		[DeviceType.MULTI_OSC]: {
			displayName: generateTranslation('Multi Osc'),
			configSchema: JSON.stringify(MultiOscOptions),
			mappingsSchemas: stringifyMappingSchema(MultiOscMappings),
		},
		[DeviceType.OBS]: {
			displayName: generateTranslation('Obs'),
			configSchema: JSON.stringify(ObsOptions),
			mappingsSchemas: stringifyMappingSchema(ObsMappings),
		},
		[DeviceType.OSC]: {
			displayName: generateTranslation('Osc'),
			configSchema: JSON.stringify(OscOptions),
			mappingsSchemas: stringifyMappingSchema(OscMappings),
		},
		[DeviceType.PANASONIC_PTZ]: {
			displayName: generateTranslation('Panasonic PTZ'),
			actions: PanasonicPTZActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(PanasonicPTZOptions),
			mappingsSchemas: stringifyMappingSchema(PanasonicPTZMappings),
		},
		[DeviceType.PHAROS]: {
			displayName: generateTranslation('Pharos'),
			actions: PharosActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(PharosOptions),
			mappingsSchemas: stringifyMappingSchema(PharosMappings),
		},
		[DeviceType.QUANTEL]: {
			displayName: generateTranslation('Quantel'),
			actions: QuantelActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(QuantelOptions),
			mappingsSchemas: stringifyMappingSchema(QuantelMappings),
		},
		[DeviceType.SHOTOKU]: {
			displayName: generateTranslation('Shotoku'),
			configSchema: JSON.stringify(ShotokuOptions),
			mappingsSchemas: stringifyMappingSchema(ShotokuMappings),
		},
		[DeviceType.SINGULAR_LIVE]: {
			displayName: generateTranslation('Singular Live'),
			configSchema: JSON.stringify(SingularLiveOptions),
			mappingsSchemas: stringifyMappingSchema(SingularLiveMappings),
		},
		[DeviceType.SISYFOS]: {
			displayName: generateTranslation('Sisyfos'),
			actions: SisyfosActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(SisyfosOptions),
			mappingsSchemas: stringifyMappingSchema(SisyfosMappings),
		},
		[DeviceType.SOFIE_CHEF]: {
			displayName: generateTranslation('Sofie Chef'),
			actions: SofieChefActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(SofieChefOptions),
			mappingsSchemas: stringifyMappingSchema(SofieChefMappings),
		},
		[DeviceType.TCPSEND]: {
			displayName: generateTranslation('Tcp Send'),
			actions: TcpSendActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(TcpSendOptions),
			mappingsSchemas: stringifyMappingSchema(TcpSendMappings),
		},
		[DeviceType.TELEMETRICS]: {
			displayName: generateTranslation('Telemetrics'),
			configSchema: JSON.stringify(TelemetricsOptions),
			mappingsSchemas: stringifyMappingSchema(TelemetricsMappings),
		},
		[DeviceType.TRICASTER]: {
			displayName: generateTranslation('Tricaster'),
			configSchema: JSON.stringify(TricasterOptions),
			mappingsSchemas: stringifyMappingSchema(TricasterMappings),
		},
		[DeviceType.UDP_SEND]: {
			displayName: generateTranslation('Udp Send'),
			actions: UdpSendActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(UdpSendOptions),
			mappingsSchemas: stringifyMappingSchema(UdpSendMappings),
		},
		[DeviceType.VISCA_OVER_IP]: {
			displayName: generateTranslation('Visca Over IP'),
			actions: ViscaOverIPActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(ViscaOverIPOptions),
			mappingsSchemas: stringifyMappingSchema(ViscaOverIPMappings),
		},
		[DeviceType.VIZMSE]: {
			displayName: generateTranslation('Viz MSE'),
			actions: VizMSEActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(VizMSEOptions),
			mappingsSchemas: stringifyMappingSchema(VizMSEMappings),
		},
		[DeviceType.VMIX]: {
			displayName: generateTranslation('Vmix'),
			actions: VmixActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(VmixOptions),
			mappingsSchemas: stringifyMappingSchema(VmixMappings),
		},
		[DeviceType.WEBSOCKET_CLIENT]: {
			displayName: generateTranslation('Websocket Client'),
			actions: WebsocketClientActions.actions.map(stringifyActionSchema),
			configSchema: JSON.stringify(WebsocketClientOptions),
			mappingsSchemas: {},
		},

	},
}
